### ISSUE TITLE
Cloning of zmap asset inventory script

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/kali-setup-script#2]
On line 357, the script tries to clone the zmap asset inventory script into

```
/root/Downloads
```

However in the latest Kali, there is no Downloads directory. Script should detect user folder and clone into the appropriate downloads directory.

**Comment by TheTechromancer** [comment]
Bug fixed.  Keep in mind this script assumes you are running as the root user.  Non-root users are not supported.
